# 剪刀末端执行器配置参数
# 这些参数用于配置剪刀相对于机械臂末端的变换矩阵

# 剪刀变换矩阵的平移部分 (x, y, z)
# 默认值：[0.01, 0.02, 0.11] 米
scissor_x_tolerance: 0.02    # x方向位置容差 (米)
scissor_y_tolerance: 0.03    # y方向位置容差 (米)  
scissor_z_tolerance: 0.05    # z方向位置容差 (米)

# 剪刀变换矩阵的旋转部分
# 当前设置为单位矩阵 (eye(3))，表示无旋转
# 如果需要调整旋转，可以修改arm_control_node.cpp中的initializeScissorTransform()方法

# 位置容差说明：
# - x_tolerance: 剪刀在机械臂末端坐标系下x方向的允许偏差范围
# - y_tolerance: 剪刀在机械臂末端坐标系下y方向的允许偏差范围
# - z_tolerance: 剪刀在机械臂末端坐标系下z方向的允许偏差范围
# 
# 这些容差用于判断果实是否在剪刀的有效工作范围内
# 如果果实位置超出容差范围，系统会认为无法安全采摘
